# run: conda env create -n <name> --file environment.yml
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pytorch::pytorch=1.10.2
  - pytorch::torchvision=0.11.3
  - pytorch::torchaudio=0.10.2
  - cudatoolkit=11.3
  - pip
  - pip:
      - pillow==9.0.1
      - transformers==4.16.2
      - sentencepiece==0.1.96
      - typer==0.4.1
      - opencv-python==3.4.2.17
      - scikit-image==0.14.2
      - scipy==1.1.0
      - tqdm==4.65.0
